# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categorie_text',
            new_name='category_text',
        ),
    ]
