# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='score',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=0, max_length=5),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
