# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamname',
            name='category',
        ),
        migrations.DeleteModel(
            name='Teamname',
        ),
    ]
