# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_category_scoringcriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='criteria',
            field=models.ManyToManyField(blank=True, to='teams.ScoringCriteria'),
        ),
    ]
