# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 15:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_category_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
