# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20171105_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
